# 22k-4005 Mujtaba Saqib BAI-5A

# Task 1

Occupancy dataset contains four attributes i-e "Humidity, Light, CO2 and Humidity ratio".
• Apply KNN to find if occupancy is possible or not (0 or 1) based on "Humidity,
Light and Humidity Ratio" only. Train on "Occupancy_train.txt" and Test on
"Occupancy_test.txt". You need to do thefollowing then :
• Run this KNN Algorithm for n_neighbors (K) from 1 to 10. You will get 10 different
accuracies.Print all the accuracies. Then print the highest accuracy and also the
value of K at which you got the highest accuracy.

In [83]:
import pandas as pd

In [44]:
df = pd.read_csv("DataTest.csv")
df.head()

Unnamed: 0              date  Temperature   Humidity       Light  \
0           1  11-02-2015 14:48      21.7600  31.133333  437.333333   
1           2  11-02-2015 14:49      21.7900  31.000000  437.333333   
2           3  11-02-2015 14:50      21.7675  31.122500  434.000000   
3           4  11-02-2015 14:51      21.7675  31.122500  439.000000   
4           5  11-02-2015 14:51      21.7900  31.133333  437.333333   

           CO2  HumidityRatio  Occupancy  
0  1029.666667       0.005021          1  
1  1000.000000       0.005009          1  
2  1003.750000       0.005022          1  
3  1009.500000       0.005022          1  
4  1005.666667       0.005030          1

In [45]:
df1 = pd.read_csv("DataTraining.csv")
df1.head()

Unnamed: 0              date  Temperature  Humidity  Light     CO2  \
0           1  04-02-2015 17:51        23.18   27.2720  426.0  721.25   
1           2  04-02-2015 17:51        23.15   27.2675  429.5  714.00   
2           3  04-02-2015 17:53        23.15   27.2450  426.0  713.50   
3           4  04-02-2015 17:54        23.15   27.2000  426.0  708.25   
4           5  04-02-2015 17:55        23.10   27.2000  426.0  704.50   

   HumidityRatio  Occupancy  
0       0.004793          1  
1       0.004783          1  
2       0.004779          1  
3       0.004772          1  
4       0.004757          1

In [53]:
#testing data
test_data_X = df.iloc[:, [3, 4, 6]]
test_data_X.head()

Humidity       Light  HumidityRatio
0  31.133333  437.333333       0.005021
1  31.000000  437.333333       0.005009
2  31.122500  434.000000       0.005022
3  31.122500  439.000000       0.005022
4  31.133333  437.333333       0.005030

In [55]:
test_data_y = df.iloc[:, [-1]]
test_data_y.head()

Occupancy
0          1
1          1
2          1
3          1
4          1

In [58]:
#training data
train_data_X = df1.iloc[:, [3, 4, 6]]
train_data_X.head()

Humidity  Light  HumidityRatio
0   27.2720  426.0       0.004793
1   27.2675  429.5       0.004783
2   27.2450  426.0       0.004779
3   27.2000  426.0       0.004772
4   27.2000  426.0       0.004757

In [59]:
train_data_y = df1.iloc[:, [-1]]
train_data_y.head()

Occupancy
0          1
1          1
2          1
3          1
4          1

In [178]:
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier

In [63]:
i = 0
acc_list = []

for i in range(1,11):
    
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(train_data_X,train_data_y)
    y_pred = knn.predict(test_data_X)
    acc = accuracy_score(train_data_y, y_pred)
    acc_list.append(acc)    

C:\Users\mujta\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\mujta\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\mujta\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\mujta\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_sam

In [64]:
print(acc_list)

[0.9997543902738548, 0.9920176839002824, 0.9917720741741373, 0.9905440255434115, 0.9891931720496132, 0.9896843915019035, 0.9893159769126857, 0.9891931720496132, 0.9878423185558148, 0.98808792828196]


In [65]:
print("highest accuracy ", max(acc_list))

highest accuracy  0.9997543902738548


# Task 2

TASK 2 :
Now instead of using built-in library, write your own code for kNN classifier from scratch.
Runon iris dataset. Use 80/20 split. Print accuracy and confusion matrix at the end. You
must use thefollowing chi squared distance function :

In [214]:
import numpy as np
from sklearn.datasets import load_iris

In [215]:
iris = load_iris()
X = iris.data  
y = iris.target

In [216]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [217]:
epsilon = 1e-10
dist_matrix = np.zeros((len(X_test), len(X_train)))

In [218]:
#chi square implementation
for i in range(len(X_test)):
    for j in range(len(X_train)):
        dist_matrix[i, j] = np.sum(((X_train[j]-X_test[i])**2) / (X_train[j]+X_test[i]+epsilon))

In [219]:
print("Chi-Square distance ")
print(dist_matrix)

Chi-Square distance 
[[3.42632047 2.42072778 0.06865396 ... 3.00988463 0.07129227 0.46395773]
 [0.32436262 0.07068815 2.05850633 ... 0.11220467 1.69393974 3.91829528]
 [7.11292025 5.56983021 0.88532036 ... 6.33948822 1.38468133 0.14011166]
 ...
 [5.69180096 4.23952694 0.43969356 ... 5.04352157 0.8517948  0.02201734]
 [0.14546744 0.35974171 2.57904123 ... 0.27258138 1.9147629  4.56851042]
 [0.18003029 0.37236866 2.52057971 ... 0.26556699 1.88105641 4.48107571]]


In [220]:
from sklearn.metrics import confusion_matrix

In [221]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred2 = model.predict(X_test)
print(confusion_matrix(y_test,y_pred2))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


# Task 3

In [353]:
cancer = pd.read_csv("cancer patient data sets.csv")

Perform EDA

In [354]:
cancer.head()

index Patient Id  Age  Gender  Air Pollution  Alcohol use  Dust Allergy  \
0      0         P1   33       1              2            4             5   
1      1        P10   17       1              3            1             5   
2      2       P100   35       1              4            5             6   
3      3      P1000   37       1              7            7             7   
4      4       P101   46       1              6            8             7   

   OccuPational Hazards  Genetic Risk  chronic Lung Disease  ...  Fatigue  \
0                     4             3                     2  ...        3   
1                     3             4                     2  ...        1   
2                     5             5                     4  ...        8   
3                     7             6                     7  ...        4   
4                     7             7                     6  ...        3   

   Weight Loss  Shortness of Breath  Wheezing  Swallowing Difficulty  \
0            4                    2         2                      3   
1            3                    7         8                      6   
2            7                    9         2                      1   
3            2                    3         1                      4   
4            2                    4         1                      4   

   Clubbing of Finger Nails  Frequent Cold  Dry Cough  Snoring   Level  
0                         1              2          3        4     Low  
1                         2              1          7        2  Medium  
2                         4              6          7        2    High  
3                         5              6          7        5    High  
4                         2              4          2        3    High  

[5 rows x 26 columns]

In [355]:
cancer = cancer.drop(['index','Patient Id','Gender'],axis=1)

In [356]:
cancer.shape

(1000, 23)

In [357]:
cancer.columns

Index(['Age', 'Air Pollution', 'Alcohol use', 'Dust Allergy',
       'OccuPational Hazards', 'Genetic Risk', 'chronic Lung Disease',
       'Balanced Diet', 'Obesity', 'Smoking', 'Passive Smoker', 'Chest Pain',
       'Coughing of Blood', 'Fatigue', 'Weight Loss', 'Shortness of Breath',
       'Wheezing', 'Swallowing Difficulty', 'Clubbing of Finger Nails',
       'Frequent Cold', 'Dry Cough', 'Snoring', 'Level'],
      dtype='object')

In [358]:
cancer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Age                       1000 non-null   int64 
 1   Air Pollution             1000 non-null   int64 
 2   Alcohol use               1000 non-null   int64 
 3   Dust Allergy              1000 non-null   int64 
 4   OccuPational Hazards      1000 non-null   int64 
 5   Genetic Risk              1000 non-null   int64 
 6   chronic Lung Disease      1000 non-null   int64 
 7   Balanced Diet             1000 non-null   int64 
 8   Obesity                   1000 non-null   int64 
 9   Smoking                   1000 non-null   int64 
 10  Passive Smoker            1000 non-null   int64 
 11  Chest Pain                1000 non-null   int64 
 12  Coughing of Blood         1000 non-null   int64 
 13  Fatigue                   1000 non-null   int64 
 14  Weight Loss              

In [359]:
cancer.describe()

Age  Air Pollution  Alcohol use  Dust Allergy  \
count  1000.000000      1000.0000  1000.000000   1000.000000   
mean     37.174000         3.8400     4.563000      5.165000   
std      12.005493         2.0304     2.620477      1.980833   
min      14.000000         1.0000     1.000000      1.000000   
25%      27.750000         2.0000     2.000000      4.000000   
50%      36.000000         3.0000     5.000000      6.000000   
75%      45.000000         6.0000     7.000000      7.000000   
max      73.000000         8.0000     8.000000      8.000000   

       OccuPational Hazards  Genetic Risk  chronic Lung Disease  \
count           1000.000000   1000.000000           1000.000000   
mean               4.840000      4.580000              4.380000   
std                2.107805      2.126999              1.848518   
min                1.000000      1.000000              1.000000   
25%                3.000000      2.000000              3.000000   
50%                5.000000      5.000000              4.000000   
75%                7.000000      7.000000              6.000000   
max                8.000000      7.000000              7.000000   

       Balanced Diet      Obesity      Smoking  ...  Coughing of Blood  \
count    1000.000000  1000.000000  1000.000000  ...        1000.000000   
mean        4.491000     4.465000     3.948000  ...           4.859000   
std         2.135528     2.124921     2.495902  ...           2.427965   
min         1.000000     1.000000     1.000000  ...           1.000000   
25%         2.000000     3.000000     2.000000  ...           3.000000   
50%         4.000000     4.000000     3.000000  ...           4.000000   
75%         7.000000     7.000000     7.000000  ...           7.000000   
max         7.000000     7.000000     8.000000  ...           9.000000   

           Fatigue  Weight Loss  Shortness of Breath     Wheezing  \
count  1000.000000  1000.000000          1000.000000  1000.000000   
mean      3.856000     3.855000             4.240000     3.777000   
std       2.244616     2.206546             2.285087     2.041921   
min       1.000000     1.000000             1.000000     1.000000   
25%       2.000000     2.000000             2.000000     2.000000   
50%       3.000000     3.000000             4.000000     4.000000   
75%       5.000000     6.000000             6.000000     5.000000   
max       9.000000     8.000000             9.000000     8.000000   

       Swallowing Difficulty  Clubbing of Finger Nails  Frequent Cold  \
count            1000.000000               1000.000000    1000.000000   
mean                3.746000                  3.923000       3.536000   
std                 2.270383                  2.388048       1.832502   
min                 1.000000                  1.000000       1.000000   
25%                 2.000000                  2.000000       2.000000   
50%                 4.000000                  4.000000       3.000000   
75%                 5.000000                  5.000000       5.000000   
max                 8.000000                  9.000000       7.000000   

         Dry Cough      Snoring  
count  1000.000000  1000.000000  
mean      3.853000     2.926000  
std       2.039007     1.474686  
min       1.000000     1.000000  
25%       2.000000     2.000000  
50%       4.000000     3.000000  
75%       6.000000     4.000000  
max       7.000000     7.000000  

[8 rows x 22 columns]

Check the dataset is balance or not (using target variable “Label”)

In [360]:
cancer['Level'].value_counts()

High      365
Medium    332
Low       303
Name: Level, dtype: int64

Check whether there is any empty records, categorical feature, duplicate records, if yes
then handle this and give a brief explanation why you have chosen this technique in a
text cell or “jupyter/colab”

In [361]:
cancer.isnull().sum()

Age                         0
Air Pollution               0
Alcohol use                 0
Dust Allergy                0
OccuPational Hazards        0
Genetic Risk                0
chronic Lung Disease        0
Balanced Diet               0
Obesity                     0
Smoking                     0
Passive Smoker              0
Chest Pain                  0
Coughing of Blood           0
Fatigue                     0
Weight Loss                 0
Shortness of Breath         0
Wheezing                    0
Swallowing Difficulty       0
Clubbing of Finger Nails    0
Frequent Cold               0
Dry Cough                   0
Snoring                     0
Level                       0
dtype: int64

In [362]:
cancer.duplicated().sum()

881

Check the correlation of your dataset and perform feature selection using Pearson
Correlation

In [363]:
def correlation(dataset, threshold):
    col_corr = set() 
    corr_matrix = dataset.corr()  

    for i in range(len(corr_matrix.columns)):
        for j in range(i):
            if abs(corr_matrix.iloc[i, j]) > threshold: 
                colname = corr_matrix.columns[i] 
                col_corr.add(colname)

    return col_corr


corr_features = correlation(df, 0.4) 
print(f'Number of correlated features: {len(corr_features)}')

cancer = cancer.drop(corr_features, axis=1)

cancer.head()

Number of correlated features: 0


C:\Users\mujta\AppData\Local\Temp\ipykernel_20368\3926018615.py:3: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  corr_matrix = dataset.corr()


Age  Air Pollution  Alcohol use  Dust Allergy  OccuPational Hazards  \
0   33              2            4             5                     4   
1   17              3            1             5                     3   
2   35              4            5             6                     5   
3   37              7            7             7                     7   
4   46              6            8             7                     7   

   Genetic Risk  chronic Lung Disease  Balanced Diet  Obesity  Smoking  ...  \
0             3                     2              2        4        3  ...   
1             4                     2              2        2        2  ...   
2             5                     4              6        7        2  ...   
3             6                     7              7        7        7  ...   
4             7                     6              7        7        8  ...   

   Fatigue  Weight Loss  Shortness of Breath  Wheezing  Swallowing Difficulty  \
0        3            4                    2         2                      3   
1        1            3                    7         8                      6   
2        8            7                    9         2                      1   
3        4            2                    3         1                      4   
4        3            2                    4         1                      4   

   Clubbing of Finger Nails  Frequent Cold  Dry Cough  Snoring   Level  
0                         1              2          3        4     Low  
1                         2              1          7        2  Medium  
2                         4              6          7        2    High  
3                         5              6          7        5    High  
4                         2              4          2        3    High  

[5 rows x 23 columns]

Analyze your dataset and think if feature scaling is required or not? If yes then apply any
scaling technique based on your distribution.

In [364]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [365]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

print(X_train)

[[ 0.0697672  -0.81013252 -0.93376358 ... -0.27932124 -0.91929611
  -0.61535347]
 [-0.34123252 -0.81013252 -0.93376358 ... -0.82835563 -0.4230499
   0.74642461]
 [-1.08103203 -0.81013252  1.06359167 ... -1.37739002  1.56193496
   2.10820269]
 ...
 [-0.17683263 -0.81013252  0.06491405 ... -0.82835563  0.07319632
  -1.29624251]
 [-0.17683263  1.23436595 -0.93376358 ...  1.36778192  0.56944253
   2.78909173]
 [-0.75223225  1.23436595 -1.4331024  ...  1.9168163   1.56193496
   1.42731365]]


Split your dataset in training , testing and validation. Train split will be 80% and test will
be 20% . In validation split your training samples will be 70% and validation set will be
30%. Briefly describe why we use validation set in a text cell. Declare Random_state=0

In [366]:
X = cancer.drop(columns=['Level'])
y = cancer['Level']

In [367]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [368]:
X_train, X_validate, y_train, y_validate = train_test_split(X,y,test_size=0.3,random_state=0)

Apply KNN and check model training and testing accuracy.

In [369]:
knn = KNeighborsClassifier(n_neighbors=20)
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)

train_accuracy = knn.score(X_train,y_train)
print(f"training accuracy {train_accuracy*100}")

test_accuracy = accuracy_score(y_test,y_pred)
print(f"testing accuracy {test_accuracy*100}")

training accuracy 92.85714285714286
testing accuracy 94.0


In [370]:
knn = KNeighborsClassifier(n_neighbors=20)
knn.fit(X_train,y_train)
y_pred = knn.predict(X_validate)

train_accuracy = knn.score(X_train,y_train)
print(f"training accuracy {train_accuracy*100}")

test_accuracy = accuracy_score(y_validate,y_pred)
print(f"testing accuracy {test_accuracy*100}")

training accuracy 92.85714285714286
testing accuracy 93.0


# TASK 5

• Apply KNN and check model training and testing accuracy.

Compare the accuracies by trying different algorithms, combine all the training and
testing accuracies of auto, KDTress , brute etc. to compare their performance. Do analyze
what you have observed and where we have used different algorithms? What is the
impact of changing algorithm on accuracy and testing time?

In [412]:
df_cancer = pd.read_csv("cancer patient data sets.csv")

In [413]:
df_cancer.head()

index Patient Id  Age  Gender  Air Pollution  Alcohol use  Dust Allergy  \
0      0         P1   33       1              2            4             5   
1      1        P10   17       1              3            1             5   
2      2       P100   35       1              4            5             6   
3      3      P1000   37       1              7            7             7   
4      4       P101   46       1              6            8             7   

   OccuPational Hazards  Genetic Risk  chronic Lung Disease  ...  Fatigue  \
0                     4             3                     2  ...        3   
1                     3             4                     2  ...        1   
2                     5             5                     4  ...        8   
3                     7             6                     7  ...        4   
4                     7             7                     6  ...        3   

   Weight Loss  Shortness of Breath  Wheezing  Swallowing Difficulty  \
0            4                    2         2                      3   
1            3                    7         8                      6   
2            7                    9         2                      1   
3            2                    3         1                      4   
4            2                    4         1                      4   

   Clubbing of Finger Nails  Frequent Cold  Dry Cough  Snoring   Level  
0                         1              2          3        4     Low  
1                         2              1          7        2  Medium  
2                         4              6          7        2    High  
3                         5              6          7        5    High  
4                         2              4          2        3    High  

[5 rows x 26 columns]

In [414]:
df_cancer = df_cancer.drop(['index','Patient Id','Gender'],axis=1)

In [415]:
df_cancer.columns

Index(['Age', 'Air Pollution', 'Alcohol use', 'Dust Allergy',
       'OccuPational Hazards', 'Genetic Risk', 'chronic Lung Disease',
       'Balanced Diet', 'Obesity', 'Smoking', 'Passive Smoker', 'Chest Pain',
       'Coughing of Blood', 'Fatigue', 'Weight Loss', 'Shortness of Breath',
       'Wheezing', 'Swallowing Difficulty', 'Clubbing of Finger Nails',
       'Frequent Cold', 'Dry Cough', 'Snoring', 'Level'],
      dtype='object')

In [416]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [417]:
knn = KNeighborsClassifier(n_neighbors=20,algorithm='kd_tree')
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)

train_accuracy = knn.score(X_train,y_train)
print(f"training accuracy {train_accuracy*100}")

test_accuracy = accuracy_score(y_test,y_pred)
print(f"testing accuracy {test_accuracy*100}")

training accuracy 91.0
testing accuracy 91.5


In [422]:
knn = KNeighborsClassifier(n_neighbors=25, algorithm='brute')
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)

train_accuracy = knn.score(X_train,y_train)
print(f"training accuracy {train_accuracy*100}")

test_accuracy = accuracy_score(y_test,y_pred)
print(f"testing accuracy {test_accuracy*100}")

training accuracy 91.625
testing accuracy 93.5


In [421]:
knn = KNeighborsClassifier(n_neighbors=25, algorithm='ball_tree')
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)

train_accuracy = knn.score(X_train,y_train)
print(f"training accuracy {train_accuracy*100}")

test_accuracy = accuracy_score(y_test,y_pred)
print(f"testing accuracy {test_accuracy*100}")

training accuracy 91.625
testing accuracy 93.5
